### ISSUE TITLE
Problem while building flash.bin for NXPEVK_iMX8M_Mini_2GB

### ISSUE THREAD

**Issue by ShiaujiuanChen** [ms-iot/imx-iotcore#128]
Build NXPEVK_iMX8M_Mini_2GB flash.bin according to the steps of [Building and Updating Firmware for ARM64](https://github.com/ms-iot/imx-iotcore/blob/public_preview/Documentation/build-arm64-firmware.md)

Linux environment: Linux Virtual Machine

- The differences between **NXPEVK_iMX8M_Mini_2GB** and NXPEVK_iMX8M_4GB as follows:
[build_flasn_bin.txt](https://github.com/ms-iot/imx-iotcore/files/3532674/build_flasn_bin.txt)

### U-Boot
make **_imx8mm_evk_nt_defconfig_**
make

### Arm Trusted Firmware
make PLAT=**_imx8mm_** SPD=opteed bl31

### OP-TEE OS
make PLATFORM=imx PLATFORM_FLAVOR=**_mx8mmevk_** \
  CFG_TEE_CORE_DEBUG=y CFG_TEE_CORE_LOG_LEVEL=3  CFG_UART_BASE=0x30890000 \
  CFG_RPMB_FS=y CFG_RPMB_TESTKEY=y CFG_RPMB_WRITE_KEY=y CFG_REE_FS=n \
  CFG_TA_DEBUG=y CFG_TEE_CORE_TA_TRACE=1 CFG_TEE_TA_LOG_LEVEL=2 \
  CFG_IMXCRYPT=y CFG_CORE_HEAP_SIZE=98304

### Imx-mkimage
cp ../../firmware-imx-8.1/firmware/ddr/synopsys/lpddr4_pmu_train_*.bin .
cp ../../firmware-imx-8.1/firmware/hdmi/cadence/signed_hdmi_imx8m.bin .
cp ../../optee_os/out/arm-plat-imx/tee.bin .
cp ../../imx-atf/build/**_imx8mm_**/release/bl31.bin .
cp ../../u-boot/u-boot-nodtb.bin  .
cp ../../u-boot/spl/u-boot-spl.bin .
cp ../../u-boot/arch/arm/dts/**_fsl-imx8mm-evk.dtb_** .
cp ../../u-boot/tools/mkimage .

make SOC=**_iMX8MM flash_spl_uboot_**

- dd flash.bin to SD card
`dd if=flash.bin of=/dev/sdc bs=512 seek=66`

- Boot iMX8M Mini EVK Board from SD card
[COM3_log_20190821.txt](https://github.com/ms-iot/imx-iotcore/files/3524442/COM3_log_20190821.txt)
[COM4_log_20190821.txt](https://github.com/ms-iot/imx-iotcore/files/3524467/COM4_log_20190821.txt)

- **Problem:** op-tee switches to normal world boot, but there is no u-boot booting message
D/TC:0 init_primary_helper:930 Primary CPU switching to normal world boot

- dd the pre-built flash.bin included in the imx-iotcore repo, image boots into Windows IoT Core successfully.

What are the problems with these steps?

**Comment by neilsh-msft** [comment]
There are two issues:
1: ATF reserves the UART we use for boot output and kernel debugging for trust zone.  Apply the following patch to ATF:
index aa1c336e..db97553a 100644
--- a/plat/imx/imx8mm/imx8mm_bl31_setup.c
+++ b/plat/imx/imx8mm/imx8mm_bl31_setup.c
@@ -310,8 +310,8 @@ void bl31_early_platform_setup2(u_register_t arg0, u_register_t arg1,

        /* Assign M4 to domain 1 */
        mmio_write_32(IMX_RDC_BASE + 0x204, 0x1);
-       mmio_write_32(IMX_RDC_BASE + 0x518, 0xfc);
-       mmio_write_32(IMX_RDC_BASE + 0x5A4, 0xf3);
+//     mmio_write_32(IMX_RDC_BASE + 0x518, 0xfc); // UART4
+//     mmio_write_32(IMX_RDC_BASE + 0x5A4, 0xf3); // UART2

2: mkimage for imx8mm should not have signed_hdmi_imx8m.bin.  The iMX8M Mini platform does not have an integrated HDMI controller on the SOC.  Remove the file from your mkimage directory and rebuild.

**Comment by ShiaujiuanChen** [comment]
Hi, @neilsh-msft ,

Thank you very much.
