### ISSUE TITLE
Issue #125 fix breaks case handling for non-mount builds

### ISSUE THREAD

**Issue by TGoodhew** [ms-iot/imx-iotcore#135]
The changes introduced in #125 break case handling for local cloned builds in WSL via /mnt/c.

The repo is to follow the clones from the firmware documentation and then change to the /mnt/c/<<imx-source>>/build/firmware/HummingBoardEdge_iMX6Q_2GB directory and run make.

**Comment by dmcilvaney** [comment]
Thanks, I'll take a look at it.

**Comment by TGoodhew** [comment]
Thanks.

TonyG

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by TGoodhew** [comment]
Actually I can’t work around by setting the entire directory to case sensitive as that breaks the VS project ☹

TonyG

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
From: Tony Goodhew <tony_goodhew@hotmail.com>
Sent: Monday, September 16, 2019 10:24:39 AM
To: ms-iot/imx-iotcore <reply@reply.github.com>; ms-iot/imx-iotcore <imx-iotcore@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [ms-iot/imx-iotcore] Issue #125 fix breaks case handling for non-mount builds (#135)

Thanks.

TonyG

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by dmcilvaney** [comment]
Set the /build/firmware/`<board>`/u-boot  and /build/firmware/`<board>`/optee folders to case sensitive, those are the only two which matter.

**Comment by TGoodhew** [comment]
Thanks – That appears to have worked.

TonyG

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by dmcilvaney** [comment]
Should be fixed in the makefile as well, it snuck past our CI since we run those in native Linux vms.

**Comment by TGoodhew** [comment]
Thanks again - Verified the make file fix on my machine
