### ISSUE TITLE
Hummingboard2 fails to boot on custom carrierboard

### ISSUE THREAD

**Issue by kiwikissling** [ms-iot/imx-iotcore#3]
I'm running a HummingBoard2 on a custom carrier board. This carrier board is destined to be deployed as an in-car telemetry device, with no user interface. It has no HDMI or audio hardware. 

I have the pulled and built December `imx-iotcore` public preview, and this boots fine on a Hummingboard2 Edge. However the boot of the same FFU on the Hummingboard2 on my carrierboard freezes very early on. 

Here's a diff of the first part of the boot: ![](https://user-images.githubusercontent.com/5044716/50198701-90815300-03b1-11e9-9304-98d2b7ca53ff.PNG)

Our carrierboard ('Scout') on the right freezes after the 
`In: serial` 
`Out: serial`
`Err: serial`

I have tried removing various combinations of IMX drivers from the FFU build, but to no avail - the boot always freezes at the same point.  

Can anyone suggest possible causes, or things I could investigate further?

Thanks and regards,
Andrew

**Comment by dvescovi1** [comment]
Where did you remove the driver?  at the os level?
Since it is freezing very early I would suspect the issue is more likely in the boot loader or the UEFI init code.
From the dump it looks like the uboot code.

**Comment by dvescovi1** [comment]
Also most display drivers are output only (unless it has CEC detection) so even if there is no display attached it does not stall the boot. Things like touch screen circuitry is a different story though.

**Comment by kiwikissling** [comment]
@dvescovi1 , Thanks for coming back to me on this. Yes, I removed the drivers from HummingBoardEdge_iMX6Q_2GB_DeviceFM.xml and the FFU built fine without them. No touch screen, but Scout does include an on-board, USB-driven cellmodem chip. 

One of the puzzling things here is that we were already wrestling with a boot issue on Kayla, but at that time Scout got deep into the boot process, ie well past the point shown above, before suffering a TA Panic. We were look for the cause of that problem when the IMX public preview (this project) launched, so we switched.

As you can probably see, I'm not much of an embedded expert. Is the uBoot code something I have access to ... to edit/build?

**Comment by dvescovi1** [comment]
Yea, you can build it all. Its best to understand the complete boot process as it is quite involved. The documentation is pretty good though. The boot loader can be found at the SolidRun GitHub repo. I like to just remove the uefi file from the SD card and boot it. It should just stay in the boot loader and if you have the serial terminal attached you can play around with all the boot loader commands. Make sure that all works first. From there you can dig into the UEFI code … a bit more challenging but everything is pretty much discoverable. Continue working up the boot strap tree till you find where in the process it is stalling.

**Comment by jordanrh1** [comment]
It looks like it's freezing in U-Boot when it tries to initialize network. The issues could be related to pin muxing differences or ethernet PHY differences between your carrier and the Hummingboard. My recommendation would be to insert prints into the u-boot code to help narrow down where it's failing. The following resources should be helpful.

[Firmware Boot Documentation](https://github.com/ms-iot/imx-iotcore/blob/public_preview/Documentation/boot.md)
[How to build firmware](https://github.com/ms-iot/imx-iotcore/blob/public_preview/Documentation/build-firmware.md)

**Comment by kiwikissling** [comment]
Jon Nettleton of Solid-run.com is supporting us with this issue.
