### ISSUE TITLE
default app for ARM64 NXPEVK_IMX8M_Mini_2GB platform

### ISSUE THREAD

**Issue by UweSteinkohl** [ms-iot/imx-iotcore#65]

**Comment by UweSteinkohl** [comment]
Hello,

when I rebuild the NXPEVK_IMX8M_Mini_2GB platform and run the image on my NXP EVK-kit the default app isn't started. Instead, I get a blue screen with a list of apps. The first item in the list is the default app, but when I click on the list element it isn't started. How can I start it?
![Screenshot_2019-04-16_07-45-28](https://user-images.githubusercontent.com/31481344/56223016-44979f80-606d-11e9-9f7f-57316c4cf5a6.jpg)

**Comment by neilsh-msft** [comment]
On the iMX8, the IoT Core Default App isn't part of the image, nor is it included in the IoT packages.  Currently it relies on a few Nuget packages that haven't been ported to ARM64 yet.  The first item in the list in the screenshot you included is a different application,

The IoT Core Default App has been made open source and information about the application including a link to the github repo is here:  https://docs.microsoft.com/en-us/windows/iot-core/develop-your-app/iotcoredefaultapp

**Comment by UweSteinkohl** [comment]
thank you for your answer. Meanwhile, I cloned the github iot core repo, added an arm64 configuration to the defaultapp and rebuild it successfully for the imx8m mini evk. thank you for your help.
