### ISSUE TITLE
IoT remote server on I.MX8 mini

### ISSUE THREAD

**Issue by dvescovi1** [ms-iot/imx-iotcore#71]
I noticed I am not able to start the IoT Remote server on the i.MX8 mini.
Everything else is running so far.

Status says it is "enabled at boot but currently not running".

When I check the check box I get "Windows IoT Remote Server enabled at boot, but could not be started"

**Comment by neilsh-msft** [comment]
The Windows IoT remote server isn't built for ARM64 devices.  Internally we want to deprecate it entirely and replace it, but that probably won't happen for 6 months to a year.  Sorry.

**Comment by dvescovi1** [comment]
Thanks for a straight answer.
