### ISSUE TITLE
win10iot for imx8mq 

### ISSUE THREAD

**Issue by cjt0701** [ms-iot/imx-iotcore#81]
hi all
I have genetated the ffu,but i how to make a sd card boot image for imx8mq.The dash board has only support imx6/7.

**Comment by christopherco** [comment]
The dashboard has not been updated to reflect i.mx8 but it is the same option as the imx6/7.

Edit: Adding a bit more background - the imx6/7 option just applies the FFU you supply to the target disk. All the BSP and OS components are present in the FFU itself. imx8 FFUs work the same way.

**Comment by cjt0701** [comment]
hi @christopherco
Uboot can't start, do not have any log.I am sure the boot config is sd card.The sd clk  pin has output。

**Comment by christopherco** [comment]
Which iMX8M board are you using? Also what is the baud rate of your serial debug console?

**Comment by dvescovi1** [comment]
just rebuilt i.MX8M EVK image … booted fine.
Rebuilt firmware and rebuilt image … also booted fine.

**Comment by cjt0701** [comment]
Hi christopherco and dvescovi1 

the board has booted,but the hdmi output resolution is only 720P.How do i set the output resolution with 1080P?

**Comment by neilsh-msft** [comment]
You'd need to modify U-Boot to set the correct timing for 1080P.  You'll need to follow up on the NXP iMX8 community support https://community.nxp.com/community/imx/content.

**Comment by cjt0701** [comment]
thank you

**Comment by christopherco** [comment]
Closing issue for now. If you have more questions or issues, feel free to reopen if it along the same topic or post a new issue.
